### ISSUE TITLE
'output' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by CindyJuarezTowle** [noahDess/corenlp-js-prefab#1]
Hi I'm trying to run the example.js file and I get this error from the index.js file when it runs into the line "output=$(wget --post-data \'text to send to server\' \'localhost..........".

Is this writing to a webpack file or object called output? I'm NOT using webpack. If this is due to webpack is there a way around it? If it's not, what could be causing the error?

**Comment by noahDess** [comment]
This has nothing to do with webpack. Do you have wget installed?

**Comment by CindyJuarezTowle** [comment]
Yes I have installed wget for windows.

**Comment by noahDess** [comment]
I have never done very much development on windows, so no guarantees. I would try removing the bold text from the index.js of the corenlp-js-interface npm dependence  '**output=$(**wget --post-data '+"'"+stringToProcess+"' "+"'localhost:"+portNumber+'/?properties={"annotators": '+'"'+annotatorsString+'", "outputFormat": "'+outputFormatString+'"'+"}' -**q**O -**) && echo $output"**,{ encoding: 'utf8' }

**Comment by CindyJuarezTowle** [comment]
You mean to this?
let termOutput = execSync('=(wget --post-data '+"'"+stringToProcess+"' "+"'localhost:"+portNumber+'/?properties={"annotators": '+'"'+annotatorsString+'", "outputFormat": "'+outputFormatString+'"'+"}' -O -)",{ encoding: 'utf8' });

This gives me "The requested name is valid, but no data of the requested type was found" for each word. Then it throws an "unable to resolve host address '\'localhost'", and again for 'parse','outputformat', and 'json'

**Comment by noahDess** [comment]
I am unfortunately unable to help you here directly as I do not have Windows set up for development.

As many development oriented projects particularly web development projects have either nonexistent or second class support for Windows it is a good idea to run code in some UNIX system. Microsoft knows this so they made [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/faq) or you can install Linux on bare metal.

I may have put the funky bash in the command for a reason like that last error.

**Comment by CindyJuarezTowle** [comment]
Okay. Well thank you for your help. I really appreciate it.

**Comment by noahDess** [comment]
I'll add a requires bash warning

**Comment by CindyJuarezTowle** [comment]
I fixed this issue. It's a single vs double quote issue on the windows cmd.

 If you're on windows, replace the code with this: 

```
let cmd = 'wget --post-data '+"\""+stringToProcess+"\" "+"\"localhost:"+portNumber+'/?properties={"annotators": '+'"'+annotatorsString+'", "outputFormat": "'+outputFormatString+'"'+"}\" -qO -";
let termOutput = execSync(cmd,{ encoding: 'utf8' });
return termOutput;
```
